name: hr2o_frontend
description: AI Smart Scheduler Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2
  
  # UI
  cupertino_icons: ^1.0.2
  http: ^1.6.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
